# Generated by Django 4.2.7 on 2024-08-20 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name (e.g. Dodge)",
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Name must be greater than 1 character",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Nickname must be greater than 1 character",
                            )
                        ],
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                ("comments", models.CharField(max_length=200)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autos.make"
                    ),
                ),
            ],
        ),
    ]
