# Generated by Django 4.2.7 on 2024-08-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question_text",
        ),
    ]
