# Generated by Django 4.2.7 on 2024-08-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_text_question_question_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="text",
            new_name="choice_text",
        ),
    ]
